#!/usr/bin/env python3

import os
import sys
import subprocess
import shutil
from pathlib import Path

def run_command(command):
    try:
        subprocess.run(command, check=True)
    except subprocess.CalledProcessError as e:
        print(f"Error running command: {command}")
        sys.exit(1)

def install_dependencies():
    if os.path.exists("/etc/debian_version"):
        print("Detected Debian/Ubuntu")
        run_command(["sudo", "apt", "update"])
        run_command(["sudo", "apt", "install", "-y", "mpd", "mpc"])
    elif os.path.exists("/etc/fedora-release"):
        print("Detected Fedora")
        run_command(["sudo", "dnf", "install", "-y", "mpd", "mpc"])
    elif os.path.exists("/etc/arch-release"):
        print("Detected Arch Linux")
        run_command(["sudo", "pacman", "-S", "--noconfirm", "mpd", "mpc"])
    else:
        print("Unsupported distribution. Please install MPD manually.")
        sys.exit(1)

def setup_config():
    home = Path.home()
    mpd_config_dir = home / ".config" / "mpd"
    mpd_playlist_dir = mpd_config_dir / "playlists"

    # Create directories
    mpd_config_dir.mkdir(parents=True, exist_ok=True)
    mpd_playlist_dir.mkdir(parents=True, exist_ok=True)

    mpd_conf_path = mpd_config_dir / "mpd.conf"

    if not mpd_conf_path.exists():
        print(f"Creating default configuration at {mpd_conf_path}")
        config_content = """# Music Player Daemon Configuration
# Generated by setup_mpd.py

# Directories
music_directory         "~/Music"
playlist_directory      "~/.config/mpd/playlists"

# Database
db_file                 "~/.config/mpd/mpd.db"

# Logging
log_file                "~/.config/mpd/mpd.log"
log_level               "default"

# Network
bind_to_address         "127.0.0.1"
port                    "6600"

# Unix Socket
bind_to_address         "~/.config/mpd/mpd.sock"

# Permissions
default_permissions     "read,add,control,admin"

# Behavior
auto_update "yes"
auto_update_depth "6"
restore_paused "yes"
metadata_to_use "artist,album,title,genre,date,musicbrainz_albumid"

# Limits
max_playlist_length     "18446744073709551615"
max_command_list_size   "18446744073709551615"
max_output_buffer_size  "18446744073709551615"

# Audio Output - PipeWire (primary)
audio_output {
    type                "pipewire"
    name                "PipeWire Output"
}

# Audio Output - HTTPD (Streaming)
audio_output {
    type "httpd"
    name "Computer"
    encoder "lame"
    port "8000"
    format "44100:16:2"
    bind_to_address "0.0.0.0"
    bitrate "192"
}

# Audio Output - FIFO (Visualizer)
audio_output {
    type                    "fifo"
    name                    "visualizer"
    path                    "/tmp/mpd.fifo"
    format                  "44100:16:2"
    mixer_type              "null"
}
"""
        with open(mpd_conf_path, "w", encoding="utf-8") as f:
            f.write(config_content)
    else:
        print(f"Configuration file already exists at {mpd_conf_path}. Skipping creation.")

def main():
    print("Setting up MPD...")
    install_dependencies()
    setup_config()

    if shutil.which("systemctl"):
        print("Enabling and starting MPD user service...")
        run_command(["systemctl", "--user", "enable", "--now", "mpd"])
        print("MPD started. Run 'mpc update' to scan your music library.")
    else:
        print("Systemd not found. Please start MPD manually.")

if __name__ == "__main__":
    main()